name: Workflow 4
on:
  workflow_run:
    workflows: ["Workflow 3"]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Workflow 4
        run: echo "Workflow 4 is running (triggered by Workflow 3)..."
